configure-terminal small changes

diff --git a/.local/bin/configure-terminal b/.local/bin/configure-terminal
--- a/.local/bin/configure-terminal
+++ b/.local/bin/configure-terminal
@@ -2,8 +2,8 @@
 
 main () {
 	MAIN_STATUS=0
-	pkg-update > /dev/null || MAIN_STATUS=1
-	install_misc || return # contains curl for later 
+	pkg-update > /dev/null &&
+	install_misc || { echo "Base package install failed!!!" >&2; return 1; } # contains curl for later 
 	install_zsh || MAIN_STATUS=1
 	install_ranger || MAIN_STATUS=1
 	install_vim || MAIN_STATUS=1
@@ -18,9 +18,9 @@ main () {
 
 install_zsh () {
 	echo "Installing ZSH!"
-	sudo "$PCKMNG" install -y zsh || return 1
+	sudo "$PCKMNG" install -y zsh || return 
 	if [ "$SHELL" != "$(which zsh)" ]; then
-	  sudo chsh -s "$(which zsh)" "$USER" || return 1
+	  sudo chsh -s "$(which zsh)" "$USER" || return 
 	else
 	  echo "You are already using zsh."
 	fi
@@ -56,28 +56,28 @@ install_misc () {
 install_mise () {
 	echo "Installing Mise!"	
 	if [ "$PCKMNG" = "dnf" ]; then
-	    sudo dnf copr enable jdxcode/mise -y &> /dev/null || return 1	
+	    sudo dnf copr enable jdxcode/mise -y &> /dev/null || return 
 	elif [ "$PCKMNG" = "apt" ]; then
 	    sudo install -dm 755 /etc/apt/keyrings &&
 	    curl -fSs https://mise.jdx.dev/gpg-key.pub | sudo tee /etc/apt/keyrings/mise-archive-keyring.asc > /dev/null &&
 	    echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list > /dev/null &&
-		sudo apt update || return 1
+		sudo apt update || return 
 	fi
 	sudo "$PCKMNG" install -y mise &> /dev/null && 
 	mise use --global node@lts > /dev/null && 
 	mise use --global java@21 > /dev/null &&
-	npm install -g @openai/codex # TODO isto noutro lado?
+	npm install -g @openai/codex # TODO isto noutro lado?, deve falhar em novas instalacoes
 }
 
 install_ghostty () {
 	echo "Installing Ghostty!"	
 	if [ "$PCKMNG" = "dnf" ]; then
-	    sudo dnf copr enable scottames/ghostty -y &> /dev/null || return 1
+	    sudo dnf copr enable scottames/ghostty -y &> /dev/null || return 
 	elif [ "$PCKMNG" = "apt" ]; then
 	    # Ghostty
 	    curl -fsSL https://deb.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | sudo gpg --dearmor --yes -o /usr/share/keyrings/deb.griffo.io.gpg &&
 	    echo "deb [signed-by=/usr/share/keyrings/deb.griffo.io.gpg] https://deb.griffo.io/apt trixie main" | sudo tee /etc/apt/sources.list.d/deb.griffo.io.list > /dev/null &&
-		sudo apt update || return 1
+		sudo apt update || return 
 	fi
 	sudo "$PCKMNG" install -y ghostty kitty-terminfo
 }
