install yadm clone block fix

diff --git a/.local/bin/install-yadm b/.local/bin/install-yadm
--- a/.local/bin/install-yadm
+++ b/.local/bin/install-yadm
@@ -34,15 +34,20 @@ cd - > /dev/null
 
 # Clone the dotfiles repo
 export GIT_SSH_COMMAND="ssh -o IdentityAgent=none -o IdentitiesOnly=yes -i $SSH_DIR/id_ed25519_sk_rk"
-yadm clone git@github.com:josbarros/dotfiles.git 2> /dev/null
-yadm gitconfig user.email "joserui@joseruibarros.com"
-yadm gitconfig user.name "José Rui Barros"
-
-# Check if everythign worked
-if [ $? -ne 0 ]; then 
-    echo "Something went wrong"!
+yadm clone git@github.com:josbarros/dotfiles.git 2> /dev/null || {
+    echo "yadm clone failed" >&2
     exit 1
-fi
+}
+
+yadm gitconfig user.email "joserui@joseruibarros.com" || {
+    echo "failed to set yadm git user.email" >&2
+    exit 1
+}
+
+yadm gitconfig user.name "José Rui Barros" || {
+    echo "failed to set yadm git user.name" >&2
+    exit 1
+}
 
 # Finish off
 rm -rf ~/.gnupg
