small install yadm update

diff --git a/.local/bin/install-yadm b/.local/bin/install-yadm
--- a/.local/bin/install-yadm
+++ b/.local/bin/install-yadm
@@ -1,13 +1,13 @@
 #!/bin/sh
 
 main () {
-	install_yadm || { echo "yadm installation failed!" >&2; return 1;}
 	SSH_DIR="$HOME/.ssh"
    	SSH_KEY="$SSH_DIR/id_ed25519_sk_rk"
-	config_ssh || { echo "ssh config failed!" >&2; return 1;}
-	config_repo || { echo "yadm repo configuration failed!" >&2; return 1;}
-	gnupg_cleanup || { echo "gnupg cleanup failed!" >&2; return 1;}
-	echo "Succssess! Please log off now to refresh .profile"
+	install_yadm &&
+	config_ssh &&
+	config_repo &&
+	gnupg_cleanup || { echo "Something failed!" >&2; return 1;}
+	echo "Success! Please log off now to refresh .profile"
 }
 
 install_yadm () {
@@ -15,7 +15,7 @@ install_yadm () {
 	# Add yadm repo before upgrading
 	if [ -d /etc/dnf/ ]; then
 	    sudo dnf config-manager addrepo --overwrite --from-repofile=https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_42/home:TheLocehiliosan:yadm.repo 2> /dev/null &&
-	    sudo dnf install -y yadm > /dev/null
+	    sudo dnf install -y yadm
 	elif [ -d /etc/apt/ ]; then
 	    sudo apt-get update > /dev/null && sudo apt-get install -y yadm
 	else
@@ -46,7 +46,7 @@ config_repo () {
 	# Clone the dotfiles repo
 	export GIT_SSH_COMMAND="ssh -o IdentityAgent=none -o IdentitiesOnly=yes -i \"$SSH_KEY\""
 	if [ ! -d "$(yadm introspect repo)" ]; then
-		yadm clone git@github.com:josbarros/dotfiles.git > /dev/null || return
+		yadm clone git@github.com:josbarros/dotfiles.git || return
 	fi
 	yadm gitconfig user.email "joserui@joseruibarros.com" &&
 	yadm gitconfig user.name "José Rui Barros"
